### ISSUE TITLE
clientRequestValidation not working with camel REST DSL

### ISSUE THREAD

**Issue by nadworny** [apache/camel-quarkus#3129] opened 2021-09-23 16:31 UTC
# Description
I have activated the `clientRequestValidation` and added `hibernate-validator` extension to [rest-json](https://github.com/apache/camel-quarkus-examples/tree/main/rest-json) example. When I send an invalid request, I'm not getting a `400` error code. Unless I misunderstood the validation feature described [here](https://camel.apache.org/manual/latest/rest-dsl.html#_client_request_validation)? If so, any idea how to validate the request in a generic way for all the rest endpoints?

# Expected behaviour
I would expect the endpoint to return `400`.

# Actual behaviour
A `500` is returned.

# How to reproduce
Add hibernate extension: `mvn quarkus:add-extension -Dextensions="hibernate-validator"`

Replace this line https://github.com/apache/camel-quarkus-examples/blob/b1352cd4c0d2a1b7b17ba73c3aca410f516d42f3/rest-json/src/main/java/org/acme/rest/json/Routes.java#L47 with the following:
```java
restConfiguration().bindingMode(RestBindingMode.json).clientRequestValidation(true);
```

Add a new test in the line https://github.com/apache/camel-quarkus-examples/blob/b1352cd4c0d2a1b7b17ba73c3aca410f516d42f3/rest-json/src/test/java/org/acme/rest/json/RestJsonTest.java#L56 as follows:
```java
/* Test validation */
given()
        .body("{\"name2\": \"Pear\", \"description\": \"Winter fruit\"}")
        .header("Content-Type", "application/json")
        .when()
        .post("/fruits")
        .then()
        .statusCode(400);
```

# Environment
openjdk version "11.0.11" 2021-04-20
macos 11.6 (20G165)
https://github.com/apache/camel-quarkus-examples version: b1352cd4c0d2a1b7b17ba73c3aca410f516d42f3

**Comment by ppalaga** [comment] 2021-09-27 07:25
It sounds like this is not Camel Quarkus specific behavior. 
@davsclaus is the REST DSL request validation also expected to cover the situation when the json body cannot be deserialized to the requested Java type (like here due to a misspelled json attribute)?

**Comment by davsclaus** [comment] 2021-09-27 09:27
No the request validation is only to match the Content-Type and Accept HTTP headers that the client send to Camel, and if they is accepted in the Rest DSL, where you can configure what a REST path supports.

This validator does not touch the message body/payload.

**Comment by davsclaus** [comment] 2021-09-27 09:29
And also if there are missing body / query parameters if they were set to be required in the Rest DSL

**Comment by davsclaus** [comment] 2021-09-27 09:29
So its working as designed, to get an error code for invalid parsing json data, then you can use onException and set the http error code you want.

**Comment by davsclaus** [comment] 2021-09-27 09:53
We can likely improved this
https://issues.apache.org/jira/browse/CAMEL-17006

**Comment by nadworny** [comment] 2021-09-29 13:56
Thanks @davsclaus. I see that the jira issue is resolved. Can I test it in this case?

**Comment by davsclaus** [comment] 2021-09-30 06:56
Yeah its in the upcoming Camel 3.12.0 release

**Comment by davsclaus** [comment] 2021-11-14 19:41
Closing as latest camel-quarkus is upgraded to Camel 3.12

**Closed by davsclaus** 2021-11-14 19:41 UTC
