### ISSUE TITLE
NullPointerException when starting with quarkus:dev goal

### ISSUE THREAD

**Issue by sobkowiak** [apache/camel-quarkus#828] opened 2020-03-01 19:58 UTC
I have checked out the 1.0.0-M3 tag and tried to start the `timer-log` sample using `mvn clean compile quarkus:dev`. The result is

````
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:71)
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
        at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
        at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
        at java.nio.file.Paths.get(Paths.java:84)
        at io.quarkus.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:307)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:91)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)

````
The same with previous versions. I tried also hello world created from scratch (without Camel) and it works (with the same Quarkus version)

My Java and Maven versions

 ```
mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /home/ksobkowiak/.sdkman/candidates/maven/current
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /home/ksobkowiak/work/ttseiii/soft-knative/jvm/graalvm-ce-java8-20.0.0/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.5.5-200.fc31.x86_64", arch: "amd64", family: "unix"
```

**Comment by aldettinger** [comment] 2020-03-25 12:01
Thanks for taking a look @sobkowiak, I've checked the 1.0.0-M3 tags but I'm not able to reproduce this issue. Could you please check the same against 1.0.0-M5 (it's quarkus 1.3.0.Final under the hood).

Also, the quarkus issue [#6168](https://github.com/quarkusio/quarkus/issues/6168) looks very [similar](https://github.com/quarkusio/quarkus/issues/6168#issuecomment-565719810), could you please try the [provided reproducer](https://github.com/quarkusio/quarkus/issues/6168#issuecomment-565651818) to check whether you would be hitting this issue.

**Comment by ppalaga** [comment] 2020-06-10 11:55
This happens when an example is run unchanged inside the Camel Quarkus source tree. You need to do one of the following: 

(a) use `mvn clean compile quarkus:dev -DnoDeps` instead of `mvn clean compile quarkus:dev` or 

(b) replace `<artifactId>camel-quarkus-build-parent</artifactId>` in the example's pom.xml with `<artifactId>camel-quarkus-bom</artifactId>`. 

The option (b) is documented in https://camel.apache.org/camel-quarkus/latest/user-guide/first-steps.html Thus closing as not a bug.

**Closed by ppalaga** 2020-06-10 11:55 UTC
