### ISSUE TITLE
(camel-quarkus-activemq) After switching to version 2.10.* and higher, the application does not start

### ISSUE THREAD

**Issue by koskom-alt** [apache/camel-quarkus#3998] opened 2022-08-16 10:29 UTC
Hi!
When I start the application in native mode at  2.10.* and higher version, I see the following error in the logs:
```{
  "timestamp": "2022-08-16T14:42:28.031+05:00",
  "sequence": 445,
  "loggerClassName": "org.jboss.logging.Logger",
  "loggerName": "io.quarkus.runtime.Application",
  "level": "ERROR",
  "message": "Failed to start application (with profile prod)",
  "thre adName": "main",
  "threadId": 1,
  "mdc": {
    
  },
  "ndc": "",
  "hostName": "desktop-j239tee",
  "processName": "NativeImageGeneratorRunner$JDK9Plus",
  "processId": 20068,
  "exception": {
    "refId": 1,
    "exceptionType": "java.lang.NoSuchMethodError",
    "message": "java.la ng.String.<init>([B)V",
    "frames": [
      {
        "class": "com.oracle.svm.jni.functions.JNIFunctions$Support",
        "method": "getMethodID",
        "line": 1114
      },
      {
        "class": "com.oracle.svm.jni.functions.JNIFunctions$Support",
        "method": "getMethodID",
        "line": 1099
      },
      {
        "cla ss": "com.oracle.svm.jni.functions.JNIFunctions",
        "method": "GetMethodID",
        "line": 410
      },
      {
        "class": "java.net.Inet6AddressImpl",
        "method": "getLocalHostName"
      },
      {
        "class": "java.net.InetAddress",
        "method": "getLocalHost",
        "line": 1627
      },
      {
        "class": "org. apache.activemq.util.InetAddressUtil",
        "method": "getLocalHostName",
        "line": 45
      },
      {
        "class": "org.apache.activemq.util.IdGenerator",
        "method": "<clinit>",
        "line": 63
      },
      {
        "class": "org.apache.activemq.ActiveMQConnectionFactory",
        "method": "getClient IdGenerator",
        "line": 991
      },
      {
        "class": "org.apache.activemq.ActiveMQConnectionFactory",
        "method": "createActiveMQConnection",
        "line": 379
      },
      {
        "class": "org.apache.activemq.ActiveMQConnectionFactory",
        "method": "createActiveMQConnection",
        "line": 347
      },
      {
        "class": "org.apache.activemq.ActiveMQConnectionFactory",
        "method": "createActiveMQConnection",
        "line": 304
      },
      {
        "class": "org.apache.activemq.ActiveMQConnectionFactory",
        "method": "createConnection",
        "line": 244
      },
      {
        "class": "org.apache.active mq.jms.pool.PooledConnectionFactory",
        "method": "createConnection",
        "line": 288
      },
      {
        "class": "org.apache.activemq.jms.pool.PooledConnectionFactory$1",
        "method": "makeObject",
        "line": 97
      },
      {
        "class": "org.apache.activemq.jms.pool.PooledConnectionF actory$1",
        "method": "makeObject",
        "line": 94
      },
      {
        "class": "org.apache.commons.pool2.impl.GenericKeyedObjectPool",
        "method": "create",
        "line": 780
      },
      {
        "class": "org.apache.commons.pool2.impl.GenericKeyedObjectPool",
        "method": "addObject",
        "line": 334
      },
      {
        "class": "org.apache.activemq.jms.pool.PooledConnectionFactory",
        "method": "createConnection",
        "line": 226
      },
      {
        "class": "org.apache.activemq.jms.pool.PooledConnectionFactory",
        "method": "createConnection",
        "line": 209
      },
      {
        "class": "org.springfr amework.jms.support.JmsAccessor",
        "method": "createConnection",
        "line": 196
      },
      {
        "class": "org.springframework.jms.listener.AbstractJmsListeningContainer",
        "method": "createSharedConnection",
        "line": 412
      },
      {
        "class": "org.springframework.jms.liste ner.AbstractJmsListeningContainer",
        "method": "establishSharedConnection",
        "line": 380
      },
      {
        "class": "org.springframework.jms.listener.DefaultMessageListenerContainer",
        "method": "establishSharedConnection",
        "line": 863
      },
      {
        "class": "org.springfra mework.jms.listener.AbstractJmsListeningContainer",
        "method": "doStart",
        "line": 292
      },
      {
        "class": "org.springframework.jms.listener.AbstractJmsListeningContainer",
        "method": "start",
        "line": 277
      },
      {
        "class": "org.springframework.jms.listener.Defa ultMessageListenerContainer",
        "method": "start",
        "line": 657
      },
      {
        "class": "org.apache.camel.component.jms.JmsConsumer",
        "method": "startListenerContainer",
        "line": 115
      },
      {
        "class": "org.apache.camel.component.jms.JmsConsumer",
        "method": "prepareAnd StartListenerContainer",
        "line": 188
      },
      {
        "class": "org.apache.camel.component.jms.JmsConsumer",
        "method": "doStart",
        "line": 172
      },
      {
        "class": "org.apache.camel.support.service.BaseService",
        "method": "start",
        "line": 119
      },
      {
        "class": "org.apache.camel .support.service.ServiceHelper",
        "method": "startService",
        "line": 113
      },
      {
        "class": "org.apache.camel.impl.engine.AbstractCamelContext",
        "method": "startService",
        "line": 3665
      },
      {
        "class": "org.apache.camel.impl.engine.InternalRouteStartupManager ",
        "method": "doStartOrResumeRouteConsumers",
        "line": 401
      },
      {
        "class": "org.apache.camel.impl.engine.InternalRouteStartupManager",
        "method": "doStartRouteConsumers",
        "line": 319
      },
      {
        "class": "org.apache.camel.impl.engine.InternalRouteStartupManag er",
        "method": "safelyStartRouteServices",
        "line": 213
      },
      {
        "class": "org.apache.camel.impl.engine.InternalRouteStartupManager",
        "method": "doStartOrResumeRoutes",
        "line": 147
      },
      {
        "class": "org.apache.camel.impl.engine.AbstractCamelContext",
        "metho d": "doStartCamel",
        "line": 3364
      },
      {
        "class": "org.apache.camel.impl.engine.AbstractCamelContext",
        "method": "doStartContext",
        "line": 3033
      },
      {
        "class": "org.apache.camel.impl.engine.AbstractCamelContext",
        "method": "doStart",
        "line": 2988
      },
      {
        "class": "org.apache.camel.support.service.BaseService",
        "method": "start",
        "line": 119
      },
      {
        "class": "org.apache.camel.impl.engine.AbstractCamelContext",
        "method": "start",
        "line": 2649
      },
      {
        "class": "org.apache.camel.impl.DefaultCamelContext",
        "method": "s tart",
        "line": 262
      },
      {
        "class": "org.apache.camel.quarkus.main.CamelMain",
        "method": "doStart",
        "line": 94
      },
      {
        "class": "org.apache.camel.support.service.BaseService",
        "method": "start",
        "line": 119
      },
      {
        "class": "org.apache.camel.quarkus.main.CamelMai n",
        "method": "startEngine",
        "line": 140
      },
      {
        "class": "org.apache.camel.quarkus.main.CamelMainRuntime",
        "method": "start",
        "line": 49
      },
      {
        "class": "org.apache.camel.quarkus.core.CamelBootstrapRecorder",
        "method": "start",
        "line": 45
      },
      {
        "class": "io.qua rkus.deployment.steps.CamelBootstrapProcessor$boot173480958",
        "method": "deploy_0"
      },
      {
        "class": "io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958",
        "method": "deploy"
      },
      {
        "class": "io.quarkus.runner.ApplicationImpl",
        "method": "doStart"
      },
      {
        "class": "io.quarkus.runtime.Application",
        "method": "start",
        "line": 101
      },
      {
        "class": "io.quarkus.runtime.ApplicationLifecycleManager",
        "method": "run",
        "line": 108
      },
      {
        "class": "io.quarkus.runtime.Quarkus",
        "method": "run",
        "line": 67
      },
      {
        "class": "io.quarkus.runtime.Quarkus",
        "method": "run",
        "line": 41
      },
      {
        "class": "io.quarkus.runtime.Quarkus",
        "method": "run",
        "line": 120
      },
      {
        "class": "io.quarkus.runner.GeneratedMain",
        "method": "main"
      }
    ]
  }
}
```
I guess this is related to https://github.com/apache/camel-quarkus/issues/3807
Let me ask you how can I solve this problem?

**Comment by jamesnetherton** [comment] 2022-08-16 10:35
If you can share an application that demonstrates the problem, it would help to get it fixed.

**Comment by koskom-alt** [comment] 2022-08-16 10:37
@jamesnetherton, thank you for your reply, I'll do it soon

**Comment by koskom-alt** [comment] 2022-08-16 16:33
@jamesnetherton https://github.com/koskom-alt/camel-quarkus-activemq, build image via `./mvnw package -Pnative`

**Comment by jamesnetherton** [comment] 2022-08-16 16:43
Thanks @koskom-alt! I will take a look.

**Comment by koskom-alt** [comment] 2022-08-16 17:10
@jamesnetherton, found a temporary solution, chose a class
```
import com.oracle.svm.core.annotate.AutomaticFeature;
import com.oracle.svm.core.jni.JNIRuntimeAccess;
import org.graalvm.nativeimage.hosted.Feature;

@AutomaticFeature
public class JNIRegistrationFeature implements Feature {
    public void beforeAnalysis(Feature.BeforeAnalysisAccess access) {
        JNIRuntimeAccess.register(String.class.getDeclaredConstructors());
    }
}
```

**Comment by jamesnetherton** [comment] 2022-08-16 17:55
I can't actually reproduce this problem (I bumped the Quarkus version in the project to `2.11.2.Final`). I'm assuming it's related to the environment because this extension works fine on our CI build. Maybe it's IPv6 related? But even when I force that, I do not see any issues. The application is producing / consuming messages without any issues.

**Comment by jamesnetherton** [comment] 2022-08-17 06:38
@koskom-alt, please can you give some more details about your environment? Which OS are you using?

**Comment by koskom-alt** [comment] 2022-08-17 07:42
@jamesnetherton, using windows 10, after updating to version graalvm-ce-java11-22.1.0 the problem is solved. Before that, the version was graalvm-ce-java11-21.3.0.

**Comment by jamesnetherton** [comment] 2022-08-17 08:03
> After updating to version graalvm-ce-java11-22.1.0 the problem is solved

Ok, good to hear that. I'll close the issue.

**Closed by jamesnetherton** 2022-08-17 08:03 UTC
