### ISSUE TITLE
FastHeadersMapFactory ClassNotFoundException since 1.0.0-M6

### ISSUE THREAD

**Issue by vitaB** [apache/camel-quarkus#1086] opened 2020-04-14 16:28 UTC
with the latest version the following runtime error is thrown for some example routes:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:27)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:358)
	... 1 more
Caused by: java.lang.ClassNotFoundException: org.apache.camel.component.headersmap.FastHeadersMapFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.deployment.steps.Core$factoryFinderResolver17.deploy_0(Core$factoryFinderResolver17.zig:374)
	at io.quarkus.deployment.steps.Core$factoryFinderResolver17.deploy(Core$factoryFinderResolver17.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:304)
	... 1 more
```
tested it with the kotlin-timer example:
```
package com.ditcalendar.bot

import org.apache.camel.Exchange
import org.apache.camel.quarkus.kotlin.routes
import javax.enterprise.context.ApplicationScoped
import javax.enterprise.inject.Produces

@ApplicationScoped
class Route() {
    @Produces
    fun myRoutes() = routes {
        from("timer:foo?period=1000")
                .process { e: Exchange -> e.message.body = "Hello from Kotlin!" }
                .log("\${body}")
    }
}
```
I used gradle instead of maven, but since its **working with `1.0.0-M5`**, i don't think its because of the build file. adding this here anyway for the sake of completeness:
```
import io.quarkus.gradle.tasks.QuarkusNative
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.3.71"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.3.71"
    id("io.quarkus") version "1.3.2.Final"
}

repositories {
    mavenCentral()
}

dependencies {
    val camelQuarkusVersion = "1.0.0-M6"

    implementation(enforcedPlatform("org.apache.camel.quarkus:camel-quarkus-bom:$camelQuarkusVersion"))
    implementation("org.apache.camel.quarkus:camel-quarkus-kotlin")
    implementation("org.apache.camel.quarkus:camel-quarkus-log")
    implementation("org.apache.camel.quarkus:camel-quarkus-timer")
}

tasks {
    named<QuarkusNative>("buildNative") {
        isEnableHttpUrlHandler = true
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
    freeCompilerArgs = listOf("-Xjsr305=strict")
}

val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
    annotation("javax.enterprise.inject.Produces")
}
```
You can add camel-headersmap to the dependencies and it will start again, but then the native image cannot be built.

**Comment by aldettinger** [comment] 2020-04-29 08:31
Thanks for sharing experience @vitaB :+1: 

I was not able to reproduce but I would expect that kind of issues to occur when versions are misaligned. Sharing a kind of dependency tree would help a lot here.

Strangely, I've noticed that camel-headersmap was [moved out from core](https://issues.apache.org/jira/browse/CAMEL-14887) at the very same time this issue was experienced. So I wonder if gradle would not use a camel snapshot version somehow ?

**Comment by ppalaga** [comment] 2020-04-29 12:16
The bottom line is that our examples should contain some basic tests.

**Comment by vitaB** [comment] 2020-04-29 16:51
Here is the dependency tree from the above build file
```
compileClasspath - Compile classpath for compilation 'main' (target  (jvm)).
+--- org.apache.camel.quarkus:camel-quarkus-bom:1.0.0-M6
|    +--- org.apache.camel.quarkus:camel-quarkus-kotlin:1.0.0-M6 (c)
|    +--- org.apache.camel.quarkus:camel-quarkus-log:1.0.0-M6 (c)
|    +--- org.apache.camel.quarkus:camel-quarkus-timer:1.0.0-M6 (c)
|    +--- org.apache.camel:camel-core-engine:3.1.0 (c)
|    +--- org.apache.camel.quarkus:camel-quarkus-core:1.0.0-M6 (c)
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61 (c)
|    +--- org.apache.camel:camel-log:3.1.0 (c)
|    +--- org.apache.camel:camel-timer:3.1.0 (c)
|    +--- org.apache.camel:camel-api:3.1.0 (c)
|    +--- org.apache.camel:camel-base:3.1.0 (c)
|    +--- org.apache.camel:camel-support:3.1.0 (c)
|    +--- io.quarkus:quarkus-core:1.3.2.Final (c)
|    +--- io.quarkus:quarkus-arc:1.3.2.Final (c)
|    +--- org.apache.camel.quarkus:camel-quarkus-support-common:1.0.0-M6 (c)
|    +--- io.quarkus:quarkus-development-mode-spi:1.3.2.Final (c)
|    +--- org.apache.camel:camel-main:3.1.0 (c)
|    +--- org.apache.camel:camel-core-catalog:3.1.0 (c)
|    +--- org.apache.camel:camel-microprofile-config:3.1.0 (c)
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61 (c)
|    +--- org.slf4j:slf4j-api:1.7.29 (c)
|    +--- jakarta.annotation:jakarta.annotation-api:1.3.5 (c)
|    +--- jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2 (c)
|    +--- jakarta.inject:jakarta.inject-api:1.0 (c)
|    +--- io.smallrye.config:smallrye-config:1.7.0 (c)
|    +--- org.jboss.logging:jboss-logging:3.3.2.Final (c)
|    +--- org.jboss.logmanager:jboss-logmanager-embedded:1.0.4 (c)
|    +--- org.jboss.logging:jboss-logging-annotations:2.1.0.Final (c)
|    +--- org.jboss.threads:jboss-threads:3.0.1.Final (c)
|    +--- org.jboss.slf4j:slf4j-jboss-logging:1.2.0.Final (c)
|    +--- org.graalvm.sdk:graal-sdk:19.3.1 (c)
|    +--- org.wildfly.common:wildfly-common:1.5.4.Final-format-001 (c)
|    +--- io.quarkus.arc:arc:1.3.2.Final (c)
|    +--- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:1.0.1 (c)
|    +--- org.eclipse.microprofile.config:microprofile-config-api:1.4 (c)
|    +--- jakarta.interceptor:jakarta.interceptor-api:1.2.5 (c)
|    +--- io.smallrye.config:smallrye-config-common:1.7.0 (c)
|    \--- jakarta.transaction:jakarta.transaction-api:1.3.3 (c)
+--- org.apache.camel.quarkus:camel-quarkus-kotlin -> 1.0.0-M6
|    +--- org.apache.camel:camel-core-engine:3.1.0
|    |    +--- org.apache.camel:camel-api:3.1.0
|    |    |    +--- org.apache.camel:camel-util:3.1.0
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    +--- org.apache.camel:camel-base:3.1.0
|    |    |    +--- org.apache.camel:camel-api:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-management-api:3.1.0
|    |    |    |    +--- org.apache.camel:camel-util:3.1.0 (*)
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    |    +--- org.apache.camel:camel-support:3.1.0
|    |    |    |    +--- org.apache.camel:camel-api:3.1.0 (*)
|    |    |    |    +--- org.apache.camel:camel-management-api:3.1.0 (*)
|    |    |    |    +--- org.apache.camel:camel-util:3.1.0 (*)
|    |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    |    +--- org.apache.camel:camel-util:3.1.0 (*)
|    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    +--- org.apache.camel:camel-management-api:3.1.0 (*)
|    |    +--- org.apache.camel:camel-support:3.1.0 (*)
|    |    \--- org.apache.camel:camel-util:3.1.0 (*)
|    +--- org.apache.camel.quarkus:camel-quarkus-core:1.0.0-M6
|    |    +--- io.quarkus:quarkus-core:1.3.2.Final
|    |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    |    |    +--- jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2
|    |    |    |    +--- jakarta.el:jakarta.el-api:3.0.3
|    |    |    |    +--- jakarta.interceptor:jakarta.interceptor-api:1.2.5
|    |    |    |    |    \--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    |    |    |    \--- jakarta.inject:jakarta.inject-api:1.0
|    |    |    +--- jakarta.inject:jakarta.inject-api:1.0
|    |    |    +--- io.smallrye.config:smallrye-config:1.7.0
|    |    |    |    +--- io.smallrye.config:smallrye-config-common:1.7.0
|    |    |    |    |    +--- org.eclipse.microprofile.config:microprofile-config-api:1.4
|    |    |    |    |    \--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.3.2.Final
|    |    |    |    \--- org.jboss.logging:jboss-logging:3.4.1.Final -> 3.3.2.Final
|    |    |    +--- org.jboss.logging:jboss-logging:3.3.2.Final
|    |    |    +--- org.jboss.logmanager:jboss-logmanager-embedded:1.0.4
|    |    |    |    \--- org.wildfly.common:wildfly-common:1.5.0.Final-format-001 -> 1.5.4.Final-format-001
|    |    |    +--- org.jboss.logging:jboss-logging-annotations:2.1.0.Final
|    |    |    +--- org.jboss.threads:jboss-threads:3.0.1.Final
|    |    |    |    +--- org.jboss.logging:jboss-logging:3.3.1.Final -> 3.3.2.Final
|    |    |    |    \--- org.wildfly.common:wildfly-common:1.5.0.Final -> 1.5.4.Final-format-001
|    |    |    +--- org.slf4j:slf4j-api:1.7.29
|    |    |    +--- org.jboss.slf4j:slf4j-jboss-logging:1.2.0.Final
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.21 -> 1.7.29
|    |    |    |    \--- org.jboss.logging:jboss-logging:3.4.0.Final -> 3.3.2.Final
|    |    |    +--- org.graalvm.sdk:graal-sdk:19.3.1
|    |    |    \--- org.wildfly.common:wildfly-common:1.5.4.Final-format-001
|    |    +--- io.quarkus:quarkus-arc:1.3.2.Final
|    |    |    +--- io.quarkus.arc:arc:1.3.2.Final
|    |    |    |    +--- jakarta.enterprise:jakarta.enterprise.cdi-api:2.0.2 (*)
|    |    |    |    +--- jakarta.annotation:jakarta.annotation-api:1.3.5
|    |    |    |    +--- jakarta.transaction:jakarta.transaction-api:1.3.3
|    |    |    |    \--- org.jboss.logging:jboss-logging:3.3.2.Final
|    |    |    +--- io.quarkus:quarkus-core:1.3.2.Final (*)
|    |    |    \--- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:1.0.1
|    |    +--- org.apache.camel.quarkus:camel-quarkus-support-common:1.0.0-M6
|    |    |    \--- io.quarkus:quarkus-core:1.3.2.Final (*)
|    |    +--- io.quarkus:quarkus-development-mode-spi:1.3.2.Final
|    |    +--- org.apache.camel:camel-main:3.1.0
|    |    |    +--- org.apache.camel:camel-api:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-base:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-core-engine:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-management-api:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-support:3.1.0 (*)
|    |    |    \--- org.apache.camel:camel-util:3.1.0 (*)
|    |    +--- org.apache.camel:camel-core-engine:3.1.0 (*)
|    |    +--- org.apache.camel:camel-base:3.1.0 (*)
|    |    +--- org.apache.camel:camel-core-catalog:3.1.0
|    |    |    +--- org.apache.camel:camel-api:3.1.0 (*)
|    |    |    +--- org.apache.camel:camel-tooling-model:3.1.0
|    |    |    |    \--- org.apache.camel:camel-util-json:3.1.0
|    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.29
|    |    \--- org.apache.camel:camel-microprofile-config:3.1.0
|    |         +--- org.apache.camel:camel-support:3.1.0 (*)
|    |         \--- org.eclipse.microprofile.config:microprofile-config-api:1.4
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.61
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.61
|         |    \--- org.jetbrains:annotations:13.0
|         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61
|              \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61 (*)
+--- org.apache.camel.quarkus:camel-quarkus-log -> 1.0.0-M6
|    +--- org.apache.camel.quarkus:camel-quarkus-core:1.0.0-M6 (*)
|    \--- org.apache.camel:camel-log:3.1.0
|         \--- org.apache.camel:camel-support:3.1.0 (*)
\--- org.apache.camel.quarkus:camel-quarkus-timer -> 1.0.0-M6
     +--- org.apache.camel.quarkus:camel-quarkus-core:1.0.0-M6 (*)
     \--- org.apache.camel:camel-timer:3.1.0
          \--- org.apache.camel:camel-support:3.1.0 (*)
```
the correct version of `org.apache.camel:camel-util` is there but `org.apache.camel:camel-headersmap` is missing.

I have now just tried to declare the dependencies version explicitly instead of using the bom and then the `camel-headersmap` is part of the loaded dependencies (and the error doesn't occur anymore).
```
dependencies {
    val camelQuarkusVersion = "1.0.0-M6"
    implementation("org.apache.camel.quarkus:camel-quarkus-kotlin:$camelQuarkusVersion")
    implementation("org.apache.camel.quarkus:camel-quarkus-log:$camelQuarkusVersion")
    implementation("org.apache.camel.quarkus:camel-quarkus-timer:$camelQuarkusVersion")
}
```

**Comment by lburgazzoli** [comment] 2020-04-29 17:12
I think you can probably fix it with M6 by adding 

    quarkus.camel.service.discovery.exclude-patterns = META-INF/services/org/apache/camel/headers-map-factory

to the application.properties

**Comment by ppalaga** [comment] 2020-06-09 15:51
> camel-headersmap is apparently exluded in https://github.com/apache/camel-quarkus/blob/master/poms/bom/pom.xml

Yes, we manage only those Camel bits in the runtime BOM which are used by our extensions. There is no camel-quarkus-headersmap yet. So, I'd say the reported behavior is not a bug.

I wonder whether we should create camel-quarkus-headersmap? WDYT @lburgazzoli and @jamesnetherton ?

**Comment by jamesnetherton** [comment] 2020-11-26 15:19
I believe this is fixed now. We have a `camel-quarkus-headersmap` extension with native support.

Feel free to reopen if the issue still persists.

**Closed by jamesnetherton** 2020-11-26 15:19 UTC
