### ISSUE TITLE
deadLetterChannel does not work in BaseRouteBuilder configure method

### ISSUE THREAD

**Issue by Chexpir** [apache/camel-quarkus#3436] opened 2022-01-04 12:00 UTC
Migrating to the latest (camel-quarkus 2.6.0 with camel-aws2-sqs:3.14.0), some code have stopped working:

This works 
```
from("aws2-sqs://nameofthequeue")
                .process(updateObjectProcessor);
```
but this does not work with
```
errorHandler(deadLetterChannel("aws2-sqs://nameoftheDLqueue")
                .log("Error processing message and sending to the Dead Letter Queue: Body: " + body())
                .useOriginalMessage());
```

The error I get is
```
Caused by: java.lang.IllegalArgumentException: AmazonSQSClient or accessKey and secretKey must be specified.
	at org.apache.camel.component.aws2.sqs.Sqs2Component.createEndpoint(Sqs2Component.java:73)
```
and it seems like deadLetterChannel method calls createEndpoint before AmazonSQSClient is injected.

The complete class is
```
@ApplicationScoped
public class SQSUpdateObjectConsumer extends BaseRouteBuilder {
    @Inject
    UpdateObjectProcessor updateObjectProcessor;
    
    @Override
    public void configure() {
        errorHandler(deadLetterChannel("aws2-sqs://nameoftheDLqueue")
                .log("Error processing message and sending to the Dead Letter Queue: Body: " + body())
                .useOriginalMessage());
        from("aws2-sqs://nameofthequeue")
                .process(updateObjectProcessor);
    }
```

Note: I use this parameter: `camel.component.aws2-sqs.auto-create-queue=true`

I've followed these aditional steps, but they did not bring any solution: https://camel.apache.org/camel-quarkus/next/reference/extensions/aws2-sqs.html#_optional_integration_with_quarkus_amazon_sqs

**Comment by Chexpir** [comment] 2022-01-04 14:37
@JiriOndrusek Temporary working solution for me is the following (adding sqsClient into camel Registry and explicitly adding it to the camel route):
```
        camelContext.getRegistry().bind("sqsClient", sqsClient);

        errorHandler(deadLetterChannel("aws2-sqs://nameoftheDLqueue?amazonSQSClient=#sqsClient")
                .log("Error processing message and sending to the Dead Letter Queue: Body: " + body())
                .useOriginalMessage());
```

**Comment by JiriOndrusek** [comment] 2022-01-04 14:45
@Chexpir thanks for the information. I'll try to simulate problem on my machine and will try to find a solution.

**Comment by JiriOndrusek** [comment] 2022-01-04 15:46
@Chexpir I' was able to simulate an error. Probably the same as you are seeing:
```
Caused by: java.lang.IllegalArgumentException: AmazonSQSClient or accessKey and secretKey must be specified.
	at org.apache.camel.component.aws2.sqs.Sqs2Component.createEndpoint(Sqs2Component.java:73)
	at org.apache.camel.support.DefaultComponent.createEndpoint(DefaultComponent.java:171)
	at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:934)
	... 72 more
```
To be sure: Are you using quarkus client ? (defined via quarkus properties - https://camel.apache.org/camel-quarkus/2.6.x/reference/extensions/aws2-sqs.html#_optional_integration_with_quarkus_amazon_sqs)

**Comment by Chexpir** [comment] 2022-01-05 08:06
@JiriOndrusek thanks for spending time on this!

Yes, it is the same error I was seeing myself.

Yes, I am using the quarkus client (2.6.1.Final) and I was not doing the 2 steps mentioned in your link, but I found that documentation and did test with that specific configuration (@unremovable tag and apache sync-client type) before opening the bug, and it was still failing.

**Comment by JiriOndrusek** [comment] 2022-01-05 12:05
Problem is caused by the issue in Camel. I reported it - https://issues.apache.org/jira/browse/CAMEL-17437.

I will also fix our junit tests, because this error can not be simulated on local aws (only real aws) even if deadletter is used. 

@Chexpir your workaround is correct. Once camel issue is fixed, I'll let you know (so you can remove workaround).

**Comment by JiriOndrusek** [comment] 2022-01-10 09:13
Problem is fixed on camel side (https://github.com/apache/camel/commit/4007b745170b69f81d47933e57d89a9ffd90c1a4)
I'll add tests into camel-quarkus and also I'll fix some problems with other aws2 tests (discovered during this investigation)

@Chexpir next cq release will contain camel with the fix and you'll be able to remove your workaround.

**Comment by JiriOndrusek** [comment] 2022-01-24 11:36
Could be closed. Reported issue is fixed in camel.
Test is added in PR: https://github.com/apache/camel-quarkus/pull/3448.
Following issues in tests are fixed in PR https://github.com/apache/camel-quarkus/pull/3458

**Comment by jamesnetherton** [comment] 2022-02-09 09:06
Fixed in https://github.com/apache/camel-quarkus/commit/e3a41408e5dbabfbde54528ff1c7dacd88b921a4.

**Closed by jamesnetherton** 2022-02-09 09:06 UTC
