### ISSUE TITLE
Update Release Guide

### ISSUE THREAD

**Issue by zbendhiba** [apache/camel-quarkus#3350] opened 2021-11-30 09:53 UTC
Hello,

I've had done some additional steps, regarding what we have  in the release guide here : https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html

And this is how I'd love to update the release guide : 

- When we generate the 2.6.x branch. Before pushing the branch, we need to update the antora version, but also scripts (as we push a snapshot version. See this commit as a reference : https://github.com/apache/camel-quarkus/pull/3339/commits/d4357cf7ce9c451b66654e77b50f0b8a0d78f388 
I wonder if we could automate this, using maven. Let me know
- When [we update the subversion repository](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_update_the_apache_camel_quarkus_distribution_subversion_repository.), we delete the latest version, before announcing the new one in the camel website :   For some time, the [download page ](https://camel.apache.org/download/#camel-quarkus)doesn't work.
I'd advise we keep the 2 latest versions. It could make the download page happy + Camel K is not updated yet + https://code.quarkus.io/ presents the 2 latest versions. 
Would love to have some feedback on this.
- When we add the release on the website, we must add the new version on the website too. See commit here: https://github.com/apache/camel-website/pull/691/commits/b458d786d725dacc24a7d1e7bb97434e7a1c3042
I'd advise also to just keep 2 latest versions, for same reason as precedent point.
- Review the paragraph of [updating camel-quarkus-examples ](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_upgrade_and_tag_examples). The PR must have the next version, and not the next version of snapshot. Maybe do as for the release a push of the tag and release branch ? There is a direct push to main that must be reviewed.
I can propose a PR for this update
-  [ update the quarkus platform](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_upgrade_camel_quarkus_in_quarkus_platform) : use their maven wrapper, as I had an issue with my new maven  version, getting more than 100+ files updated, due to style difference. Using the `./mvnw` instead made the PR better.

**Comment by djencks** [comment] 2021-11-30 20:42
In general we can’t predict how many older version need to be kept on the website: it depends on what other subprojects are referencing them.  I’m going to try to make this really explicit, as I proposed on the mailing list.

I’m also going to try to update the user-manual release-guide-website.adoc page to cover the website changes needed for subproject releases since they are basically the same as for camel/camel-karaf/camel-spring-boot.

Apache policy says the download page should only show “branches" for which further development is planned, and the download area should only have these releases.  Others are permanently available in  the “historical” section somewhere. When I looked recently I thought that the download area needed cleanup for most or all camel subprojects.

I think this means for camel-quarkus that there should only be one release on the download page and in the download area.  Main camel would have one short-term release and all the current LTS releases. There are going to be more doc versions visible than versions shown on the download page.

The maven updates of antora.yml are nice but not yet sophisticated enough, they are causing problems after release.

**Comment by ppalaga** [comment] 2021-12-02 16:12
> * When we generate the 2.6.x branch. Before pushing the branch, we need to update the antora version, but also scripts (as we push a snapshot version. See this commit as a reference : [d4357cf](https://github.com/apache/camel-quarkus/commit/d4357cf7ce9c451b66654e77b50f0b8a0d78f388)

Could you please explain why the replacement from `version: 2.5.x` to `version: latest`?

>   I wonder if we could automate this, using maven. Let me know

There is `commit-release-changes` profile https://github.com/apache/camel-quarkus/blob/main/pom.xml#L972-L1026 that is active for both the release commit and the commit after: https://github.com/apache/camel-quarkus/blob/main/pom.xml#L331-L332
You may want to make `tooling/scripts/update-antora-yaml.groovy` behave differently depending on `project.version.endsWith('-SNAPSHOT')` - if that's `true` it is the commit after, otherwise it is the release commit. Is that what you look for?

> * When [we update the subversion repository](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_update_the_apache_camel_quarkus_distribution_subversion_repository.), we delete the latest version, before announcing the new one in the camel website :   For some time, the [download page ](https://camel.apache.org/download/#camel-quarkus)doesn't work.
>   I'd advise we keep the 2 latest versions. It could make the download page happy + Camel K is not updated yet + https://code.quarkus.io/ presents the 2 latest versions.
>   Would love to have some feedback on this.

Sound good to me.

> * When we add the release on the website, we must add the new version on the website too. See commit here: [apache/camel-website@b458d78](https://github.com/apache/camel-website/commit/b458d786d725dacc24a7d1e7bb97434e7a1c3042)
>   I'd advise also to just keep 2 latest versions, for same reason as precedent point.

+1

> * Review the paragraph of [updating camel-quarkus-examples ](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_upgrade_and_tag_examples). The PR must have the next version, and not the next version of snapshot. Maybe do as for the release a push of the tag and release branch ? There is a direct push to main that must be reviewed.

The current text in the guide was meant to first prepare a PR with a SNAPSHOT version, let the CI test it, then merge the PR and only after that update to the release-like version, tag and push directly without running the CI. 
Yes, the release-like version can be used already in the PR. It is indeed perhaps a bit simpler. Feel free to update the guide.

Note that the part with the direct push would still be required with some modifications: One would have to fetch&reset from upstream, tag the merged commit and then push the tag. The tag was often asked for @vkasala and his friends :)

> * [ update the quarkus platform](https://camel.apache.org/camel-quarkus/next/contributor-guide/release-guide.html#_upgrade_camel_quarkus_in_quarkus_platform) : use their maven wrapper, as I had an issue with my new maven  version, getting more than 100+ files updated, due to style difference. Using the `./mvnw` instead made the PR better.

Ha, you've got me :) I thought those changes were caused by a newer Quarkus BOM generator plugin version. We should propose upgrading their wrapper, FWIW!

**Comment by djencks** [comment] 2021-12-03 04:37
I've proposed updating the instructions on updating the website after a release in https://github.com/apache/camel/pull/6497.  I think the instructions are now generic and apply to all subprojects: feedback k appreciated.

Apache policy is that the downloads page only show artifacts that are undergoing continued development.  For camel subprojects I believe this means any number of LTS releases but only one non-LTS release.

The downloads area is similarly only supposed to have the artifacts listed on the download page.... camel needs to do a lot of cleanup here.

As noted in the proposed doc updates, we can only remove a version from the docs when no other subproject is referencing it. AFAIK the only practical test is to try removing it, build the site, and look for errors.

**Comment by zbendhiba** [comment] 2021-12-23 12:28
FYI, I pushed 2 minor changes to the guide :  https://github.com/apache/camel-quarkus/pull/3413 and https://github.com/apache/camel-quarkus/pull/3409

**Closed** 2022-06-08 09:14 UTC
Labels: documentation
