### ISSUE TITLE
vertx-websocket extension

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#1507] opened 2020-07-31 08:15 UTC
There is a camel-vertx-websocket component. We need an extension for this
https://camel.apache.org/components/latest/vertx-websocket-component.html

**Comment by jamesnetherton** [comment] 2020-08-03 06:10
Duplicate of https://github.com/apache/camel-quarkus/issues/1301.

**Closed by jamesnetherton** 2020-08-03 06:10 UTC
Labels: extension
