### ISSUE TITLE
flatten-bom goal fails due to unresolved versions `org.jboss:jdk-misc:${version.jdk-misc}`

### ISSUE THREAD

**Issue by jamesnetherton** [apache/camel-quarkus#5493] opened 2023-11-09 10:02 UTC
### Bug description

Observed on the latest `quarkus-main` nightly build and when attempting to upgrade to Quarkus 3.5.1.

```
[ERROR] Failed to execute goal org.l2x6.cq:cq-maven-plugin:4.3.0:flatten-bom (flatten-bom) on project camel-quarkus-bom: Execution flatten-bom of goal org.l2x6.cq:cq-maven-plugin:4.3.0:flatten-bom failed: Additional BOM io.quarkus:quarkus-bom:3.5.1 contains unresolved versions:
[ERROR]     - org.jboss:jdk-misc:${version.jdk-misc}
```

`jdk-misc` seems to have been added to `quarkus-bom` with an unresolvable version property:

```
<dependency>
  <groupId>org.jboss</groupId>
  <artifactId>jdk-misc</artifactId>
  <version>${version.jdk-misc}</version>
  <scope>provided</scope>
</dependency>
```

I opened a discussion about it on Quarkus Zulip:

https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/jdk-misc.20in.20quarkus-bom

@ppalaga is there any way to work around it?

**Comment by zhfeng** [comment] 2023-11-09 10:18
@ppalaga it might be related to the recent change in `4.4.6`. see https://github.com/l2x6/cq-maven-plugin/commit/3a114fdc5cf56502f6666fa757b9e7d1f4319ef4

**Comment by ppalaga** [comment] 2023-11-09 20:23
The root cause is https://github.com/jboss/jboss-parent-pom/issues/236 
David has merged the fix already: https://github.com/jboss/jboss-parent-pom/pull/237

cq-maven-plugin 4.4.6 was my attempt to implement a workaround. As @zhfeng has noted I have rather implemented a new bug :) 
cq-maven-plugin 4.4.7 via https://github.com/apache/camel-quarkus/pull/5495 should workaround it properly.

**Closed** 2023-12-07 10:27 UTC
Labels: bug
