### ISSUE TITLE
Duplicate license headers in Velocity test templates

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#1843] opened 2020-09-25 13:34 UTC
We have two license headers for some reason here and elsewhere.

_Originally posted by @ppalaga in https://github.com/apache/camel-quarkus/pull/1804#discussion_r494977020_

**Comment by ppalaga** [comment] 2020-09-25 13:35
@JiriOndrusek could you please pick this one?

**Comment by JiriOndrusek** [comment] 2020-09-25 13:36
Please, assign to me. I see the reason, it was caused by my bad revert of the test code.

**Closed** 2020-09-25 19:04 UTC
