### ISSUE TITLE
Datasonnet language not supported?

### ISSUE THREAD

**Issue by gus-maurizio** [apache/camel-quarkus#2546] opened 2021-05-02 10:48 UTC
Is there a special configuration needed to support datasonnet?

**Comment by gus-maurizio** [comment] 2021-05-02 12:48
Actually adding the pom dependency straight from camel (camel-datasonnet 3.9.0) produces the following error:
```
2021-05-02 08:46:19,943 3c22fb64e5f7 quarkus181-cloudtrail-1.0.0-runner.jar[35428] WARN  [org.apa.cam.com.tim.TimerConsumer] (Camel (AppName.Cloudtrail) thread #1 - timer://foo) Error processing exchange. Exchange[4727D-0000000002]. Caused by: [org.apache.camel.CamelExecutionException - Exception occurred during execution on the exchange: Exchange[4727D-0000000002]]: org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[4727D-0000000002]
        at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
        at org.apache.camel.support.AbstractExchange.setException(AbstractExchange.java:564)
        at org.apache.camel.support.DefaultPooledExchange.setException(DefaultPooledExchange.java:31)
        at org.apache.camel.processor.TransformProcessor.process(TransformProcessor.java:78)
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:439)
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181)
        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:62)
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:167)
        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:388)
        at org.apache.camel.component.timer.TimerConsumer.sendTimerExchange(TimerConsumer.java:209)
        at org.apache.camel.component.timer.TimerConsumer$1.run(TimerConsumer.java:76)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.lang.NoClassDefFoundError: scala/collection/IterableOnce
        at org.apache.camel.language.datasonnet.DatasonnetExpression.evaluate(DatasonnetExpression.java:117)
        at org.apache.camel.processor.TransformProcessor.process(TransformProcessor.java:47)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: scala.collection.IterableOnce
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 11 more
```

**Comment by ppalaga** [comment] 2021-05-03 08:37
No, it is not supported yet. Contributions are welcome, see https://camel.apache.org/camel-quarkus/latest/contributor-guide/create-new-extension.html 
Closing as a duplicate of https://github.com/apache/camel-quarkus/issues/2078

**Closed by ppalaga** 2021-05-03 08:37 UTC
