### ISSUE TITLE
Surefire 3.0.0-M4 passing even if a build step throws an exception

### ISSUE THREAD

**Issue by ppalaga** [apache/camel-quarkus#723] opened 2020-02-14 16:10 UTC
The XsltProcessor is throwing NoSuchMethodError when the app is augmented for testing (the same exception is mentioned in #721 for the dev mode). However with maven-surefire-plugin 3.0.0-M4, this exception is swallowed and the whole build is passing and 0 tests run are reported:

```
[INFO] Running org.apache.camel.quarkus.component.xslt.it.XsltTest
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.863 s - in org.apache.camel.quarkus.component.xslt.it.XsltTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

When the maven-surefire-plugin is downgraded to 2.22.1, it fails as expected:

```
[INFO] Running org.apache.camel.quarkus.component.xslt.it.XsltTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.871 s <<< FAILURE! - in org.apache.camel.quarkus.component.xslt.it.XsltTest
[ERROR] org.apache.camel.quarkus.component.xslt.it.XsltTest  Time elapsed: 1.871 s  <<< ERROR!
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.apache.camel.quarkus.component.xslt.deployment.XsltProcessor#xsltResources threw an exception: java.lang.NoSuchMethodError: javax.xml.transform.TransformerFactory.newInstance(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljavax/xml/transform/TransformerFactory;
        at org.apache.camel.quarkus.support.xalan.XalanTransformerFactory.<init>(XalanTransformerFactory.java:41)
...
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   XsltTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildExcepti...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

I have just reported this in Quarkus: https://github.com/quarkusio/quarkus/issues/7203

**Comment by ppalaga** [comment] 2020-03-18 14:13
This should not be an issue as of Quarkus 1.3.0.Final. Sending a PR to revert back to surefire 3.0.0-M4.

**Comment by JiriOndrusek** [comment] 2020-06-16 07:29
Please, assign to me.

**Comment by JiriOndrusek** [comment] 2020-06-17 07:23
Problem is already solved in maven-surefire/master. Next version will work correctly.

**Comment by ppalaga** [comment] 2020-06-17 07:42
OK, so let's wait for 3.0.0-M5 to appear in Maven Central https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-surefire-plugin/

**Comment by aldettinger** [comment] 2020-06-18 15:36
3.0.0-M5 looks already there. Is it 3.0.0-M6 that we are waiting ?

**Comment by ppalaga** [comment] 2020-06-18 21:08
I have not seen 3.0.0-M5 on the Central when I checked last time. @JiriOndrusek could you please check if 3.0.0-M5 works for us?

**Comment by JiriOndrusek** [comment] 2020-06-19 07:15
@ppalaga @aldettinger 
3.0.0-M5 works (it contains fix https://github.com/apache/maven-surefire/commit/761851e5a58a38a3f87f1b71449a0fe452a79838)

**Comment by ppalaga** [comment] 2020-06-19 07:18
Great, would mind preparing an upgrade?

**Comment by JiriOndrusek** [comment] 2020-06-19 07:24
ok, I'll prepare PR

**Comment by JiriOndrusek** [comment] 2020-06-25 11:22
There were some failing test on CI after upgrade to surefire-plugin 3.0.0-M5. Problem was caused by using JPMS during execution of tests. There is a different behavior in default test executions on Oracle JDK and AdoptOpenJDK. Java modular system is by default turned on (since https://issues.apache.org/jira/browse/SUREFIRE-1570), but there is an option to turn it off (https://issues.apache.org/jira/browse/SUREFIRE-1531). PR turns off modular system for both JVM and native tests (and upgrades surefire-plugin as well)

**Comment by JiriOndrusek** [comment] 2020-06-26 08:03
There is another difference in test summaries between 2.22.2 and 3.0.0-M5 -> reported as https://issues.apache.org/jira/browse/SUREFIRE-1812

**Comment by ppalaga** [comment] 2021-11-26 18:29
We might want to check whether https://github.com/sormuras/junit-platform-maven-plugin could serve us as a replacement of surefire and/or failsafe plugins.

**Closed** 2023-07-06 09:11 UTC
