### ISSUE TITLE
Add camel-master extension

### ISSUE THREAD

**Issue by nicolaferraro** [apache/camel-quarkus#1476] opened 2020-07-14 12:53 UTC
The [camel-master](https://camel.apache.org/components/latest/master-component.html) component has no corresponding extension in camel-quarkus.

**Comment by jamesnetherton** [comment] 2020-07-14 12:56
Duplicate of https://github.com/apache/camel-quarkus/issues/711.

**Comment by nicolaferraro** [comment] 2020-07-14 13:09
I see @dhirajsb was working on that, should we close this?

**Comment by jamesnetherton** [comment] 2020-07-14 13:28
Yeah let's close. I'll add the other issue to the GA milestone so that we don't forget about it.

@dhirajsb are you planning to work on #711?

**Comment by jamesnetherton** [comment] 2020-07-24 14:13
Closing as its a dupe. I'll work on #711.

**Closed by jamesnetherton** 2020-07-24 14:13 UTC
