### ISSUE TITLE
Java jOOR DSL native support

### ISSUE THREAD

**Issue by essobedo** [apache/camel-quarkus#4358] opened 2022-12-23 13:27 UTC
[To support routes written in Java language in Camel-K](https://github.com/apache/camel-k/issues/3023), we have to make the extension `java-joor-dsl` compatible with the native mode.

**Comment by essobedo** [comment] 2022-12-23 13:52
The corresponding PR https://github.com/apache/camel-quarkus/pull/4359

**Comment by ppalaga** [comment] 2022-12-31 19:37
BTW we have bit older issue for this: https://github.com/apache/camel-quarkus/issues/2083 

Could we perhaps close this one as a duplicate of that one?

**Comment by essobedo** [comment] 2023-01-04 14:42
I was aware of this issue but for me, they are 2 different issues. This one is focused on the Java DSL based on jOOR while the ticket you are referring to mentions the jOOR language that is part of the jOOR component. Having the Java DSL supporting the native mode is good enough to be able to make a native compilation of Camel-K integrations written in Java.

If you want, I can have a look to https://github.com/apache/camel-quarkus/issues/2083 after this one

**Comment by ppalaga** [comment] 2023-01-05 12:25
> they are 2 different issues. 

Indeed, sorry for the noise!

**Closed** 2023-01-06 09:42 UTC
