### ISSUE TITLE
Env variable substitution doesn't work

### ISSUE THREAD

**Issue by oscerd** [apache/camel-quarkus#82] opened 2019-07-22 13:15 UTC
If you run the Integration test for AWS components, where you need the environment variables, it will fail with the following error

```
oscerd@ghost:~/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3$ mvn clean install -Dnative -Dnative-image.docker-build=true -Dnative-image.xmx=5g  -Dnative-camel
[INFO] Scanning for projects...
[INFO] 
[INFO] ---< org.apache.camel.quarkus:camel-quarkus-integration-test-aws-s3 >---
[INFO] Building Camel Quarkus :: Integration Tests :: AWS S3 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Deleting /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Skipping Rule Enforcement.
[INFO] 
[INFO] --- gmavenplus-plugin:1.7.1:execute (test-project-sanity-checks) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Using Groovy 2.5.7 to perform execute.
[INFO] Running Groovy script from file:////home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/../test-project-sanity-checks.groovy.
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (process-resource-bundles) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/src/test/resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] Building jar: /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/target/camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.19.1:build (default) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Beginning quarkus augmentation
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Beta4
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1824ms
[INFO] [io.quarkus.creator.phase.runnerjar.RunnerJarPhase] Building jar: /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/target/camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:0.19.1:native-image (native-image) @ camel-quarkus-integration-test-aws-s3 ---
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] Running Quarkus native-image plugin on Java HotSpot(TM) 64-Bit Server VM
[INFO] [io.quarkus.creator.phase.nativeimage.NativeImagePhase] docker run -v /home/oscerd/workspace/apache-camel/camel-quarkus/integration-tests/aws-s3/target:/project:z --rm --user 1000:1000 quay.io/quarkus/ubi-quarkus-native-image:19.0.2 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -J-Xmx5g -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace
[camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner:9]    classlist:   9,695.31 ms
[camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner:9]        (cap):   1,044.28 ms
[camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner:9]        setup:   2,482.74 ms
12:29:27,829 INFO  [org.apa.cam.imp.con.FastTypeConverterRegistry] Type converters loaded (core: 183, classpath: 14)
12:29:28,843 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta4
12:29:29,629 INFO  [org.xnio] XNIO version 3.7.2.Final
12:29:29,735 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.quarkus.runtime.CleanableExecutor$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of org.jboss.threads.ThreadLocalResettingRunnable$Resetter. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner:9]     analysis:  14,555.60 ms
Printing call tree to /project/reports/call_tree_camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner_20190722_122942.txt
Printing list of used classes to /project/reports/used_classes_camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner_20190722_122943.txt
Printing list of used packages to /project/reports/used_packages_camel-quarkus-integration-test-aws-s3-0.0.1-SNAPSHOT-runner_20190722_122943.txt
Error: Class initialization failed: io.quarkus.runner.ApplicationImpl1
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization failed: io.quarkus.runner.ApplicationImpl1
Detailed message:

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:219)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:733)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization failed: io.quarkus.runner.ApplicationImpl1
Detailed message:

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:564)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
	... 7 more
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.ensureClassInitialized(ConfigurableClassInitialization.java:129)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:357)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.computeInitKindAndMaybeInitializeClass(ConfigurableClassInitialization.java:92)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.maybeInitializeHosted(ConfigurableClassInitialization.java:120)
	at com.oracle.svm.hosted.SVMHost.registerType(SVMHost.java:179)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:263)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:204)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:154)
	at org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4229)
	at org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4472)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5260)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3416)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3223)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:944)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:838)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:214)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:333)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:509)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:342)
	... 34 more
Caused by: org.apache.camel.RuntimeCamelException: org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> To[aws-s3://devvox1] <<< in route: Route(route1)[From[timer:quarkus?repeatCount=1] -> [SetHeade... because of Failed to resolve endpoint: aws-s3://devvox1 due to: Cannot auto create component: aws-s3
	at org.apache.camel.RuntimeCamelException.wrapRuntimeCamelException(RuntimeCamelException.java:52)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.doInit(FastCamelRuntime.java:133)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.init(FastCamelRuntime.java:91)
	at org.apache.camel.quarkus.core.runtime.CamelRecorder.init(CamelRecorder.java:58)
	at io.quarkus.deployment.steps.CamelInitProcessor$createInitTask17.deploy_0(CamelInitProcessor$createInitTask17.zig:73)
	at io.quarkus.deployment.steps.CamelInitProcessor$createInitTask17.deploy(CamelInitProcessor$createInitTask17.zig:92)
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:312)
	... 34 more
Caused by: org.apache.camel.FailedToCreateRouteException: Failed to create route route1 at: >>> To[aws-s3://devvox1] <<< in route: Route(route1)[From[timer:quarkus?repeatCount=1] -> [SetHeade... because of Failed to resolve endpoint: aws-s3://devvox1 due to: Cannot auto create component: aws-s3
	at org.apache.camel.reifier.RouteReifier.addRoutes(RouteReifier.java:361)
	at org.apache.camel.reifier.RouteReifier.addRoutes(RouteReifier.java:106)
	at org.apache.camel.impl.AbstractCamelContext.startRoute(AbstractCamelContext.java:1084)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelContext.reifyRoutes(FastCamelContext.java:110)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.loadRoutes(FastCamelRuntime.java:178)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelRuntime.doInit(FastCamelRuntime.java:131)
	... 39 more
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: aws-s3://devvox1 due to: Cannot auto create component: aws-s3
	at org.apache.camel.impl.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:782)
	at org.apache.camel.support.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:74)
	at org.apache.camel.reifier.RouteReifier.resolveEndpoint(RouteReifier.java:120)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:117)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:123)
	at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:40)
	at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:34)
	at org.apache.camel.reifier.ProcessorReifier.makeProcessorImpl(ProcessorReifier.java:536)
	at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:497)
	at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:241)
	at org.apache.camel.reifier.RouteReifier.addRoutes(RouteReifier.java:358)
	... 44 more
Caused by: org.apache.camel.RuntimeCamelException: Cannot auto create component: aws-s3
	at org.apache.camel.impl.AbstractCamelContext.getComponent(AbstractCamelContext.java:511)
	at org.apache.camel.impl.AbstractCamelContext.getComponent(AbstractCamelContext.java:470)
	at org.apache.camel.impl.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:725)
	... 54 more
Caused by: org.apache.camel.RuntimeCamelException: Cannot auto create component: aws-s3
	at org.apache.camel.impl.AbstractCamelContext.initComponent(AbstractCamelContext.java:566)
	at org.apache.camel.impl.AbstractCamelContext.access$000(AbstractCamelContext.java:190)
	at org.apache.camel.impl.AbstractCamelContext$2.apply(AbstractCamelContext.java:495)
	at org.apache.camel.impl.AbstractCamelContext$2.apply(AbstractCamelContext.java:491)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.apache.camel.impl.AbstractCamelContext.getComponent(AbstractCamelContext.java:491)
	... 56 more
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Property with key [env:S3_REGION] using function [env] returned null value which is not allowed, from input: {{env:S3_REGION}}
	at org.apache.camel.quarkus.core.runtime.support.RuntimeSupport.lambda$bindProperties$3(RuntimeSupport.java:53)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.apache.camel.quarkus.core.runtime.support.RuntimeSupport.bindProperties(RuntimeSupport.java:43)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelContext.resolve(FastCamelContext.java:102)
	at org.apache.camel.quarkus.core.runtime.support.FastCamelContext.lambda$createComponentResolver$0(FastCamelContext.java:68)
	at org.apache.camel.impl.AbstractCamelContext.initComponent(AbstractCamelContext.java:560)
	... 61 more
Caused by: java.lang.IllegalArgumentException: Property with key [env:S3_REGION] using function [env] returned null value which is not allowed, from input: {{env:S3_REGION}}
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.getPropertyValue(DefaultPropertiesParser.java:227)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.readProperty(DefaultPropertiesParser.java:157)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.doParse(DefaultPropertiesParser.java:116)
	at org.apache.camel.component.properties.DefaultPropertiesParser$ParsingContext.parse(DefaultPropertiesParser.java:100)
	at org.apache.camel.component.properties.DefaultPropertiesParser.parseUri(DefaultPropertiesParser.java:63)
	at org.apache.camel.component.properties.PropertiesComponent.parseUri(PropertiesComponent.java:244)
	at org.apache.camel.component.properties.PropertiesComponent.parseUri(PropertiesComponent.java:170)
	at org.apache.camel.impl.AbstractCamelContext.resolvePropertyPlaceholders(AbstractCamelContext.java:2407)
	at org.apache.camel.quarkus.core.runtime.support.RuntimeSupport.lambda$bindProperties$3(RuntimeSupport.java:49)
	... 77 more
Error: Image build request failed with exit status 1
```

**Comment by ppalaga** [comment] 2019-08-01 08:40
After #72 was merged, using `quarkus.camel.defer-init-phase=true` in application.properties should solve the problem. Could you please try it, @oscerd  and eventually close this issue?

**Comment by oscerd** [comment] 2019-08-01 08:42
I will

**Comment by ppalaga** [comment] 2019-08-21 14:46
The twitter tests that use env vars https://github.com/apache/camel-quarkus/pull/138 are a good proof that the issue is solved now.

**Closed** 2019-08-29 13:30 UTC

**Comment by bradodarb** [comment] 2023-10-23 04:15
The twtter feed tests ref env var placeholders in application.properties file. 

Routes with property placeholders referencing env vars seems to remain broken.
