### ISSUE TITLE
Split package usage warning with camel-quarkus

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-quarkus#3159] opened 2021-10-06 04:43 UTC
Today I generated a quarkus project from code.quarkus.io with Camel and running `mvn quarkus:dev` got the following warning:
```
2021-10-06 13:39:47,337 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-46) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "org.apache.camel.main" found in [org.apache.camel:camel-base-engine::jar, org.apache.camel:camel-main::jar]
```

Is this something we are already aware of?

**Comment by davsclaus** [comment] 2021-10-06 04:50
Yes its fixed in Camel already, will be in the camel-quarkus 2.2.0 release

**Comment by jamesnetherton** [comment] 2021-10-06 06:21
Duplicate of https://github.com/apache/camel-quarkus/issues/2997.

> will be in the camel-quarkus 2.2.0 release

It's part of the 2.3.0 release.

**Closed by jamesnetherton** 2021-10-06 06:21 UTC

**Comment by tadayosi** [comment] 2021-10-06 06:32
Thanks guys!  Good to know that.
