### ISSUE TITLE
Using camel-quarkus-xslt-saxon in native mode ends up with java.lang.NoSuchMethodException at runtime 

### ISSUE THREAD

**Issue by bvahdat** [apache/camel-quarkus#3360] opened 2021-12-07 13:07 UTC
Starting a natively built Camel integration with the following setup:

Quarkis: `2.5.0.Final`
JDK: `GraalVM CE 21.3.0`
Maven: `3.8.3`

Where there´s a usage of `xslt-saxon` producer ends up with the following error at start-up:

```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-12-07 13:37:16,250 WARN  [org.apa.cam.qua.cor.JvmOnlyRecorder] (main) The camel-xslt-saxon extension was not tested in native mode. You may want to report about the success or failure running it in native mode on https://github.com/apache/camel-quarkus/issues?q=is%3Aissue+camel+xslt+saxon
2021-12-07 13:37:16,522 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2021-12-07 13:37:16,537 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.FailedToCreateRouteException: Failed to create route toStartMail_PIPE at: >>> To[xslt-saxon:Mail.xsl?saxonExtensionFunctions=#property] <<< in route: Route(toStartMail_PIPE)[From[direct:toStartMail_PIPE] -> [To... because of Failed to resolve endpoint: xslt-saxon://ME.xsl?saxonExtensionFunctions=#property due to: java.lang.NoSuchMethodException: org.apache.camel.component.xslt.saxon.XsltSaxonBuilder.<init>()
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:240)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:74)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:851)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:741)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2773)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:165)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2491)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2510)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:246)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:139)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:100)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:929)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: xslt-saxon://Mail.xsl?saxonExtensionFunctions=#property due to: java.lang.NoSuchMethodException: org.apache.camel.component.xslt.saxon.XsltSaxonBuilder.<init>()
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:964)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:846)
        at org.apache.camel.support.CamelContextHelper.resolveEndpoint(CamelContextHelper.java:123)
        at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:43)
        at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:36)
        at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:838)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:579)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:236)
        ... 25 more
Caused by: org.apache.camel.RuntimeCamelException: java.lang.NoSuchMethodException: org.apache.camel.component.xslt.saxon.XsltSaxonBuilder.<init>()
        at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:395)
        at org.apache.camel.impl.engine.DefaultInjector.newInstance(DefaultInjector.java:65)
        at org.apache.camel.impl.engine.DefaultInjector.newInstance(DefaultInjector.java:44)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.createXsltBuilder(XsltSaxonEndpoint.java:181)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.createXsltBuilder(XsltSaxonEndpoint.java:58)
        at org.apache.camel.component.xslt.XsltEndpoint.doInit(XsltEndpoint.java:337)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.doInit(XsltSaxonEndpoint.java:151)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84)
        at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1454)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1399)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1394)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1389)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:948)
        ... 32 more
Caused by: java.lang.NoSuchMethodException: org.apache.camel.component.xslt.saxon.XsltSaxonBuilder.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:393)
        ... 45 more

2021-12-07 13:37:16,547 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodException: org.apache.camel.component.xslt.saxon.XsltSaxonBuilder.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at org.apache.camel.support.ObjectHelper.newInstance(ObjectHelper.java:393)
        at org.apache.camel.impl.engine.DefaultInjector.newInstance(DefaultInjector.java:65)
        at org.apache.camel.impl.engine.DefaultInjector.newInstance(DefaultInjector.java:44)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.createXsltBuilder(XsltSaxonEndpoint.java:181)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.createXsltBuilder(XsltSaxonEndpoint.java:58)
        at org.apache.camel.component.xslt.XsltEndpoint.doInit(XsltEndpoint.java:337)
        at org.apache.camel.component.xslt.saxon.XsltSaxonEndpoint.doInit(XsltSaxonEndpoint.java:151)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.support.service.ServiceHelper.initService(ServiceHelper.java:84)
        at org.apache.camel.impl.engine.AbstractCamelContext.internalAddService(AbstractCamelContext.java:1454)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1399)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1394)
        at org.apache.camel.impl.engine.AbstractCamelContext.addService(AbstractCamelContext.java:1389)
        at org.apache.camel.impl.engine.AbstractCamelContext.doGetEndpoint(AbstractCamelContext.java:948)
        at org.apache.camel.impl.engine.AbstractCamelContext.getEndpoint(AbstractCamelContext.java:846)
        at org.apache.camel.support.CamelContextHelper.resolveEndpoint(CamelContextHelper.java:123)
        at org.apache.camel.reifier.SendReifier.resolveEndpoint(SendReifier.java:43)
        at org.apache.camel.reifier.SendReifier.createProcessor(SendReifier.java:36)
        at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:838)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:579)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:236)
        at org.apache.camel.reifier.RouteReifier.createRoute(RouteReifier.java:74)
        at org.apache.camel.impl.DefaultModelReifierFactory.createRoute(DefaultModelReifierFactory.java:49)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:851)
        at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:741)
        at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2773)
        at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:165)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2491)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2510)
        at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:246)
        at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:139)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:100)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:929)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

Running the same integration without native build starts and works as expected.

Following the relevant dependencies:

```
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-log</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-jta</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-narayana-jta</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-microprofile-health</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-artemis-jms</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-micrometer</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-jms</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-xpath</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-direct</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-xslt-saxon</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.camel.quarkus</groupId>
      <artifactId>camel-quarkus-controlbus</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-micrometer</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-db2</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>
```

Also the first line of the output log attracted my attention:

```
2021-12-07 13:37:16,250 WARN  [org.apa.cam.qua.cor.JvmOnlyRecorder] (main) The camel-xslt-saxon extension was not tested in native mode. You may want to report about the success or failure running it in native mode on https://github.com/apache/camel-quarkus/issues?q=is%3Aissue+camel+xslt+saxon
```

**Comment by zhfeng** [comment] 2021-12-11 00:48
yeah, I think there is https://github.com/apache/camel-quarkus/issues/1615 to add native support in ```xslt-saxon```. The contribution is welcome.

**Comment by bvahdat** [comment] 2021-12-11 09:29
Yeah you're right, that's why I gave a try with pure `xstl` having native support, but currently stuck through https://github.com/apache/camel-quarkus/issues/3374.

**Comment by ppalaga** [comment] 2021-12-14 08:08
Closing as duplicate of https://github.com/apache/camel-quarkus/issues/1615

**Closed by ppalaga** 2021-12-14 08:08 UTC
