### ISSUE TITLE
camel-quarkus-jira WatchUpdates Bug

### ISSUE THREAD

**Issue by viggo23111** [apache/camel-quarkus#5427] opened 2023-10-14 11:50 UTC
### Bug description

I have an camel endpoint: jira://watchUpdates?jiraUrl=${JIRA_URL}&username=RAW(${JIRA_USERNAME})&password=RAW(${JIRA_PASSWORD})&jql=RAW(project=CTT)&sendOnlyUpdatedField=false

To fetch issues that get updated, there is just one problem it is only the issues created before the route is started that is getting caught by the fetch, when updating the issues.  So new issues after the route is running are not getting caught by the fetch when they are updated.

This is for both creating a issue using an another route or creating it in jira (website) im not getting watchUpdates, if I dont restart the route, is there anything I can do to make this work ?

**Comment by jamesnetherton** [comment] 2023-10-14 16:25
> is there anything I can do to make this work 

I am not super familiar with how `watchUpdates` works, but could you maybe handle this by tweaking the JQL? E.g ordering the results in descending order by `id`.

**Comment by viggo23111** [comment] 2023-10-14 16:59
hmm the watchUpdates endpoint is just giving me the issue I updated something on, so I'm not getting more than one issue when the route start, the problem is the endpoint don't receive any updates if I create a Jira issue after the route have started, then the route is only trigged on those that was created before the route was started. If you want to see the issue I'm open to show you the problem :)

**Comment by jamesnetherton** [comment] 2023-10-27 07:47
Apologies for the delay in responding. I think I may have found the cause:

https://issues.apache.org/jira/browse/CAMEL-20053

**Comment by viggo23111** [comment] 2023-10-27 07:50
Hey thanks for looking into this, I would look forward to testing it when
it gets fixed :)

Den fre. 27. okt. 2023 kl. 09.48 skrev James Netherton <
***@***.***>:

**Comment by jamesnetherton** [comment] 2023-11-24 07:37
This will be fixed in the upcoming Camel Quarkus 3.6.0 release.

**Closed by jamesnetherton** 2023-11-24 07:37 UTC
Labels: bug, area/jira
