### ISSUE TITLE
SnappyCompression fails while building native image

### ISSUE THREAD

**Issue by rernas35** [apache/camel-quarkus#1910] opened 2020-10-13 08:45 UTC
Using camel-quarkus-cassandraql with version of 1.1.0 and getting the following error ; 

Error: could not find target method: protected io.netty.buffer.ByteBuf com.datastax.oss.driver.internal.core.protocol.SnappySubstitution.compressHeap(io.netty.buffer.ByteBuf)
com.oracle.svm.core.util.UserError$UserException: could not find target method: protected io.netty.buffer.ByteBuf com.datastax.oss.driver.internal.core.protocol.SnappySubstitution.compressHeap(io.netty.buffer.ByteBuf)
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:637)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:330)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:302)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:915)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:852)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:553)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

**Comment by jamesnetherton** [comment] 2020-10-13 08:54
Native builds for `camel-quarkus-cassandraql` isn't really supported at the moment. See https://github.com/apache/camel-quarkus/issues/1355. @JiriOndrusek can work on native support progress now that some of the issues seem to have been resolved?

**Comment by JiriOndrusek** [comment] 2020-10-13 09:02
@jamesnetherton @rernas35 I'll look into current state to see if more work could be done.

**Comment by ppalaga** [comment] 2020-10-26 08:41
Closing as duplicate of #1355

**Closed by ppalaga** 2020-10-26 08:41 UTC

**Comment by JiriOndrusek** [comment] 2020-10-29 10:19
@rernas35 Cassandra extension is still blocked. See https://github.com/apache/camel-quarkus/issues/1355#issuecomment-718595635
