### ISSUE TITLE
Don't publish integration tests during a Maven release

### ISSUE THREAD

**Issue by zregvart** [apache/camel-quarkus#842] opened 2020-03-03 20:04 UTC
Currently integration test artefacts such as `camel-quarkus-integration-test-aws` are published with the release. I think for 1.0 release we should not publish those. This can be done by adding:

```
<plugin>
  <artifactId>maven-deploy-plugin</artifactId>
  <configuration>
    <skip>true</skip>
  </configuration>
</plugin>
```

To https://github.com/apache/camel-quarkus/blob/master/integration-tests/pom.xml

**Comment by ppalaga** [comment] 2020-03-04 07:33
Yes, publishing the itests is typically useless, but in our case, it was a deliberate decision, because they are run inside quarkus-platform https://github.com/quarkusio/quarkus-platform/tree/master/integration-tests

**Comment by ppalaga** [comment] 2020-03-05 10:44
Can we close this one, @zregvart ?

**Comment by zregvart** [comment] 2020-03-05 11:17
Is there a use case for them being published to Maven Central, are users depending on them? If not perhaps the `<skip>` can be added in the `release` profile.

**Comment by oscerd** [comment] 2020-03-05 11:19
They are used here https://github.com/quarkusio/quarkus-platform/tree/master/integration-tests as dependency. So they must be released.

**Comment by ppalaga** [comment] 2020-03-31 15:56
It works as designed. Feel free to reopen if you feel the design is not correct.

**Closed by ppalaga** 2020-03-31 15:56 UTC
Labels: enhancement, good first issue, help wanted
