### ISSUE TITLE
jsonpath : Unexpected character ('r' (code 114)): was expecting double-quote to start field name

### ISSUE THREAD

**Issue by aldettinger** [apache/camel-quarkus#2676] opened 2021-05-26 17:14 UTC
Looks there is an issue starting with camel-quarkus 2.0.0-M1, with a route like below:
```
        from("platform-http:/hello").
        choice().when().jsonpath("$.room[?(@.temperature > 20)]").
            setBody(simple("HOT")).
        otherwise().
            setBody(constant("WARM")).
        end();
```

when invoking with restassured:
```
given().body("{room:{temperature:30}}").when().post("/hello").then().statusCode(200);
```

It produces the stack trace below:
```
2021-05-26 19:03:03,268 ERROR [org.apa.cam.pro.err.DefaultErrorHandler] (vert.x-worker-thread-0) Failed delivery for (MessageId: 1AE1D33D7D526F3-0000000000000000 on ExchangeId: 1AE1D33D7D526F3-0000000000000000). Exhausted after delivery attempt: 1 caught: org.apache.camel.ExpressionEvaluationException: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]

Message History (complete message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[route1            ] [route1            ] [from[platform-http:///hello]                                                  ] [        29]
	...
[route1            ] [choice1           ] [choice[when[jsonpath{$.room[?(@.temperature > 20)]}],otherwise[setBody[constan] [         0]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
: org.apache.camel.ExpressionEvaluationException: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:159)
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:45)
	at org.apache.camel.support.ExpressionSupport.matches(ExpressionSupport.java:36)
	at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:77)
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:71)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:463)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$2(VertxPlatformHttpConsumer.java:184)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:81)
	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:51)
	at org.apache.camel.jsonpath.JsonPathEngine.readWithInputStream(JsonPathEngine.java:231)
	at org.apache.camel.jsonpath.JsonPathEngine.doRead(JsonPathEngine.java:185)
	at org.apache.camel.jsonpath.JsonPathEngine.read(JsonPathEngine.java:105)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluateJsonPath(JsonPathExpression.java:190)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:144)
	... 17 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1814)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:713)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458)
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:79)
	... 23 more

2021-05-26 19:03:03,289 WARN  [org.apa.cam.com.pla.htt.ver.VertxPlatformHttpConsumer] (vert.x-eventloop-thread-3) Failed handling platform-http endpoint /hello. Caused by: [org.apache.camel.ExpressionEvaluationException - com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]]: org.apache.camel.ExpressionEvaluationException: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:159)
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:45)
	at org.apache.camel.support.ExpressionSupport.matches(ExpressionSupport.java:36)
	at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:77)
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:71)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:463)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$2(VertxPlatformHttpConsumer.java:184)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:81)
	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:51)
	at org.apache.camel.jsonpath.JsonPathEngine.readWithInputStream(JsonPathEngine.java:231)
	at org.apache.camel.jsonpath.JsonPathEngine.doRead(JsonPathEngine.java:185)
	at org.apache.camel.jsonpath.JsonPathEngine.read(JsonPathEngine.java:105)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluateJsonPath(JsonPathExpression.java:190)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:144)
	... 17 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1814)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:713)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458)
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:79)
	... 23 more

2021-05-26 19:03:03,317 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /hello failed, error id: b6a30169-e85f-413a-88e4-74cadfc9b4e0-1: org.apache.camel.ExpressionEvaluationException: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:159)
	at org.apache.camel.support.ExpressionAdapter.evaluate(ExpressionAdapter.java:45)
	at org.apache.camel.support.ExpressionSupport.matches(ExpressionSupport.java:36)
	at org.apache.camel.processor.FilterProcessor.matches(FilterProcessor.java:77)
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:71)
	at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:463)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:184)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$2(VertxPlatformHttpConsumer.java:184)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.jayway.jsonpath.InvalidJsonException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:81)
	at com.jayway.jsonpath.internal.ParseContextImpl.parse(ParseContextImpl.java:51)
	at org.apache.camel.jsonpath.JsonPathEngine.readWithInputStream(JsonPathEngine.java:231)
	at org.apache.camel.jsonpath.JsonPathEngine.doRead(JsonPathEngine.java:185)
	at org.apache.camel.jsonpath.JsonPathEngine.read(JsonPathEngine.java:105)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluateJsonPath(JsonPathExpression.java:190)
	at org.apache.camel.jsonpath.JsonPathExpression.evaluate(JsonPathExpression.java:144)
	... 17 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('r' (code 114)): was expecting double-quote to start field name
 at [Source: (InputStreamReader); line: 1, column: 3]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2337)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:710)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:635)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1814)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:713)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:707)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1458)
	at com.jayway.jsonpath.spi.json.JacksonJsonProvider.parse(JacksonJsonProvider.java:79)
	... 23 more


```

**Comment by JiriOndrusek** [comment] 2021-05-27 06:42
@aldettinger If you do not plan to work on this, I can assign it to me and look at it in the next weeks.

**Comment by aldettinger** [comment] 2021-05-27 07:24
@JiriOndrusek , sure please go ahead :+1:

**Comment by JiriOndrusek** [comment] 2022-01-24 12:27
This is not a bug. If you add "double quotes" to property names, it works.
```
RestAssured.given().body("{\"room\": {\"temperature\": 19 }}").when().post("/hello").then().statusCode(200);
```

Camel itself behaves just the same.

**Comment by aldettinger** [comment] 2022-01-24 15:45
Nice catch @JiriOndrusek. This behavior change occurred in camel-quarkus 2.0.0-M1. The parser may have been too relax before this. So, I agree this is not a bug.

I do not remember that a test was implemented for this, so I think we could merely close the issue as is. What do you think ?

**Closed** 2022-01-24 16:38 UTC
